CREATE TABLE admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL
);

INSERT INTO admin (username, password) VALUES ('admin', 'password');

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100),
  password VARCHAR(100)
);

INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
(1, 'Ritik Khatri', 'ritikkhatri51@gmail.com', '123'),
(2, 'rajesh ', 'rajesh123@gamil.com', '123');


CREATE TABLE packages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  duration VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  type VARCHAR(50), 
  description TEXT,
  image VARCHAR(255)
);

INSERT INTO `packages` (`id`, `title`, `duration`, `price`, `type`, `description`, `image`) VALUES
(1, 'Dehradun & Uttarakhand', '6 Nights / 5 Days', 25000.00, 'Family/Group/Couple', 'Uttarakhand, also known as the “Land of Gods”, is famous for its scenic beauty, holy rivers, peaceful hill stations, and breathtaking Himalayan views. This tour offers a perfect blend of nature, spirituality, and adventure. Explore the calm valleys of Dehradun, the picturesque hills of Mussoorie, the serene banks and yoga culture of Rishikesh, and the divine aura of Haridwar’s Ganga Aarti. Whether you are traveling with family, friends, partner traveler, this tour ensures relaxation, natural beauty, culture, and unforgettable memories.', '1762608840_8644_1762574479_4155_dhr2.jpg,1762608840_9903_1762574479_7531_dhr3.jpg,1762608855_6296_dhr4.jpg,1762664799_6278_1762574479_8194_dhr1.jpg'),
(2, 'Goa', '5 Nights / 6 Days', 23000.00, 'Family/Group/Couple', 'Goa is one of India’s most popular beach destinations, known for its golden sandy shores, blue waters, thrilling water sports, historic churches, and vibrant nightlife. This 5 Nights / 6 Days Goa Tour Package offers a perfect combination of relaxation, sightseeing, and leisure time. Enjoy the lively beaches of North Goa such as Calangute, Baga, and Vagator, explore the serene beauty of South Goa, visit the famous Basilica of Bom Jesus and Se Cathedral, and soak in the scenic views from Dona Paula. The package also includes exciting activities like water sports and an enjoyable evening River Cruise on the Mandovi River. Comfortable hotel stays, transportation, and a memorable holiday experience are included to make your trip unforgettabl', '1762607311_4591_goa2.jpg,1762666541_6908_goa.jpeg,1762666541_5678_goa3.jpg,1762666541_2589_goa4.jpg'),
(3, 'Ooty – Maysor', '8 Nights / 9 Days', 21000.00, 'Family/Group/Couple', 'Ooty, also known as Udhagamandalam, is a serene hill station located in the Nilgiri Mountains. Famous for its cool climate, lush green valleys, majestic tea gardens, and mist-covered hills, Ooty offers a refreshing escape from the busy city life. Major attractions include Botanical Garden, Ooty Lake, Doddabetta Peak, Rose Garden, and the iconic Nilgiri Mountain Toy Train, which provides a scenic journey through forests and tea plantations. It is a perfect destination for nature lovers, couples, and families. \r\n>>   Mysore, known as the Cultural Capital of Karnataka, is renowned for its royal heritage, grand architecture, and vibrant tradition. The magnificent Mysore Palace, Chamundi Hills, St. Philomena’s Church, and Mysore Zoo are among the top attractions. The city is also famous for silk sarees, sandalwood products, and rich history. Mysore beautifully blends culture, art, and historic elegance, making it a must-visit destination.', '1762667848_2141_ottyas.jpg,1762667914_1223_1762665046_2226_ottytea.jpg,1762667914_9445_1762665046_4629_otty.jpg,1762667914_8193_1762665046_7872_otty3.jpg,1762667914_1267_1762666327_1929_maysor1.jpg,1762667914_1500_1762666862_1025_otty5.jpg');





CREATE TABLE `bookings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `package_id` int(11) NOT NULL,
  `package_name` varchar(255) DEFAULT NULL,
  `hotel_id` int(11) DEFAULT NULL,
  `hotel_name` varchar(255) DEFAULT NULL,
  `hotel_star` varchar(20) DEFAULT NULL,
  `image` text DEFAULT NULL,
  `adults` int(11) NOT NULL,
  `children` int(11) NOT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `hotel` varchar(255) NOT NULL,
  `checkin` date NOT NULL,
  `checkout` date NOT NULL,
  `status` varchar(20) DEFAULT 'Confirm',
  `booked_on` timestamp NOT NULL DEFAULT current_timestamp(),
  `booking_date` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO `bookings` (`id`, `user_id`, `package_id`, `package_name`, `hotel_id`, `hotel_name`, `hotel_star`, `image`, `adults`, `children`, `price`, `hotel`, `checkin`, `checkout`, `status`, `booked_on`, `booking_date`) VALUES
(1, 2, 2, 'Goa', 15, 'Hotel Rajpurohit', '4 Star', '1762867146_5s5.jpg', 2, 0, 4400.00, '', '2025-11-17', '2025-11-25', 'Pending', '2025-11-12 05:26:48', '2025-11-12 05:26:48');



CREATE TABLE `itineraries` (
  `id` int(11) NOT NULL,
  `package_id` int(11) NOT NULL,
  `day_or_night` varchar(50) NOT NULL,
  `plan` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `itineraries` (`id`, `package_id`, `day_or_night`, `plan`) VALUES
(1, 2, '5/6', 'Day 1: Arrival in Goa\n • Arrive at Goa Airport or Railway Station\n • Transfer to hotel and check-in\n • Welcome drink on arrival (Non-Alcoholic)\n • Free time to relax or visit nearby beach\n • Overnight stay at hotel\n\nDay 2: North Goa Sightseeing\n • Breakfast at hotel\n • Visit Calangute Beach\n • Visit Baga Beach\n • Visit Candolim Beach\n • Visit Vagator Beach\n • Visit Fort Aguada\n • Water sports available at extra cost\n • Return to hotel and overnight stay\n\nDay 3: South Goa Sightseeing\n • Breakfast at hotel\n • Visit Basilica of Bom Jesus\n • Visit Se Cathedral\n • Visit St. Augustine Tower\n • Visit Mangeshi Temple or Shantadurga Temple\n • Visit Dona Paula Viewpoint\n • Visit Miramar Beach\n • Return to hotel and overnight stay\n\nDay 4: Leisure Day\n • Breakfast at hotel\n • Day free for personal activities\n • Optional activities at extra cost: Water sports, Island Trip, Shopping\n • Overnight stay at hotel\n\nDay 5: Mandovi River Cruise\n • Breakfast at hotel\n • Free time to relax at the beach or resort\n • Evening Mandovi River Cruise with music and cultural dance\n • Return to hotel and overnight stay\n\nDay 6: Departure\n • Breakfast at hotel\n • Check-out at hotel '),
(2, 1, '5/6', ' Day 1 – Arrival in Dehradun : \r\n • Arrival at Dehradun Airport / Railway Station\r\n • Meet & Greet, then transfer to the hotel\r\n • After check-in, visit Forest Research Institute, Tapkeshwar Temple\r\n • Evening free for shopping at Paltan Bazaar\r\n • Overnight stay in Dehradun\r\n\r\nDay 2 – Dehradun → Mussoorie :\r\n\r\n • After breakfast, drive to Mussoorie — the “Queen of Hills”\r\n • Visit Kempty Falls, Company Garden, Gun Hill Point, Camel’s Back Road\r\n • Evening stroll along Mall Road for shopping & street food\r\n • Overnight stay at Mussoorie\r\n\r\n🗓 Day 3 – Mussoorie Sightseeing :\r\n • Morning breakfast at the hotel\r\n • Excursion to Lal Tibba (the highest point) and Mussoorie Lake\r\n • Optional: Ropeway ride or paragliding experience (seasonal)\r\n • Dinner & overnight stay at Mussoorie\r\n\r\n🗓 Day 4 – Mussoorie → Rishikesh (85 km / 3 hrs)\r\n • Drive down to Rishikesh\r\n • Visit Lakshman Jhula, Ram Jhula, Triveni Ghat, Parmarth Niketan Ashram\r\n • Witness the evening Ganga Aarti at Triveni Ghat — a spiritual highlight\r\n • Overnight stay in Rishikesh\r\n\r\nDay 5 – Rishikesh → Haridwar  → Dehradun : \r\n • Morning transfer to Haridwar for sightseeing: Har Ki Pauri, Mansa Devi  • Temple, Daksha Mahadev Temple\r\n • Explore local markets for handicrafts & Ayurvedic products\r\n • Later return to Dehradun\r\n • Overnight stay in Dehradun\r\n\r\nDay 6 – Departure :\r\nBreakfast at hotel, check-out, and transfer to Airport / Railway Station\r\nTour ends with pleasant memories of the Himalayas \r\n'),
(3, 3, 'asdasd', 'Day 1 – Arrival in Bangalore\r\nArrive at Bangalore Airport / Railway Station\r\nMeet & greet by representative, then transfer to hotel\r\nVisit Lalbagh Botanical Garden, Cubbon Park, Vidhana Soudha, Bangalore Palace\r\nEvening at MG Road for shopping & local dining\r\nOvernight stay in Bangalore\r\n\r\n🗓 Day 2 – Bangalore → Mysore (145 km / 3 hrs)\r\nAfter breakfast, drive to Mysore (City of Palaces)\r\nEn route visit Srirangapatna (Tipu Sultan’s Fort, Dariya Daulat Palace)\r\nCheck-in at hotel\r\nEvening visit to the Mysore Palace, beautifully lit at night\r\nOvernight stay in Mysore\r\n\r\n🗓 Day 3 – Mysore Sightseeing\r\nBreakfast at hotel\r\nVisit Chamundi Hills, Nandi Bull Temple, Mysore Zoo, Brindavan Gardens (musical fountain show at night)\r\nExplore local silk saree & sandalwood shops\r\nOvernight stay in Mysore\r\n\r\n🗓 Day 4 – Mysore → Ooty (125 km / 4 hrs)\r\nMorning drive through scenic forested hills to Ooty – the “Queen of Hills”\r\nEn route visit Bandipur National Park or Mudumalai Wildlife Sanctuary\r\nCheck-in at hotel in Ooty\r\nEvening at leisure around Ooty Lake or Botanical Gardens\r\n\r\nOvernight stay in Ooty\r\n\r\n🗓 Day 5 – Ooty Sightseeing\r\n\r\nBreakfast at hotel\r\n\r\nVisit Doddabetta Peak, Tea Factory & Museum, Rose Garden, Government Botanical Garden\r\n\r\nEnjoy boating at Ooty Lake\r\n\r\nEvening walk around Charing Cross or Commercial Street\r\nOvernight stay in Ooty\r\n\r\n🗓 Day 6 – Ooty → Coonoor Excursion\r\nMorning toy train (optional) ride from Ooty to Coonoor\r\nVisit Sim’s Park, Lamb’s Rock, Dolphin’s Nose Viewpoint, and Highfield Tea Estate\r\nReturn to Ooty for overnight stay\r\n\r\n🗓 Day 7 – Ooty → Wayanad (140 km / 4 hrs)\r\nAfter breakfast, depart for Wayanad, Kerala\r\nEn route enjoy forest landscapes and waterfalls\r\nVisit Pookode Lake, Lakkidi View Point, Chain Tree, Banasura Sagar Dam\r\nCheck-in at hotel and relax\r\nOvernight stay in Wayanad\r\n\r\n🗓 Day 8 – Wayanad Sightseeing\r\nVisit Edakkal Caves, Soochipara Waterfalls, and Wayanad Wildlife Sanctuary\r\n\r\nExperience Kerala’s cultural blend and local cuisine\r\n\r\nOvernight stay in Wayanad\r\n\r\n🗓 Day 9 – Wayanad → Bangalore (280 km / 6 hrs) – Departure : \r\nBreakfast at hotel, check-out, and drive back to Bangalore\r\nDrop-off at Airport / Railway Station\r\nTour ends with sweet memories of South India');



CREATE TABLE get_in_touch (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100),
    message TEXT
);

INSERT INTO `get_in_touch` (`id`, `name`, `email`, `message`) VALUES
(1, 'rajesh', 'rajesh@gamil.com', 'Ask for package details (inclusions, hotels, sightseeing, meals, etc.)');


CREATE TABLE `hotels` (
  `id` int(11) NOT NULL,
  `package_id` int(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `location` varchar(100) NOT NULL,
  `rating` float NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `category` varchar(50) NOT NULL,
  `images` text NOT NULL,
  `description` text NOT NULL,
  `facilities` text NOT NULL,
  `food` text NOT NULL,
  `policy` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `hotels` (`id`, `package_id`, `name`, `location`, `rating`, `price`, `category`, `images`, `description`, `facilities`, `food`, `policy`) VALUES
(1, 1, 'Hotel Silver Shell', 'Near City Center / Near Bus Stand / Mall Road, Dehradun, Uttarakhand, India', 3.6, 2600.00, '3 Star', '1762924208_3star.jpg,1762924208_32.jpg,1762924208_33.avif', 'Hotel Silver Shell offers a comfortable and relaxing stay with well-furnished rooms and modern amenities. The hotel provides a peaceful environment, friendly hospitality, and easy access to nearby travel spots. Whether you are traveling with family, friends, or for business, the hotel ensures a pleasant accommodation experience with cleanliness, comfort, and warm service.', 'Clean and Comfortable Rooms, Air Conditioning, Free WiFi, Complimentary Breakfast, Room Service (Limited Hours), 24-hour Front Desk, Daily Housekeeping, In-house Restaurant or Café, Free Parking, Television with Cable Channels, Laundry Service (Paid)', 'Hotel Silver Shell features a Pure Vegetarian kitchen serving fresh and hygienically prepared meals. The in-house restaurant offers a comfortable dining ambiance where guests can enjoy a variety of North Indian, South Indian, Chinese, and Continental vegetarian dishes.\r\n•  All meals are prepared without onion and garlic options can also be provided upon request. The hotel ensures quality ingredients, clean kitchen standards, and timely meal service for a healthy and satisfying dining experience.\r\n\r\n>> Dining Highlights:\r\n    •   100% Pure Veg Menu\r\n    •    Breakfast, Lunch & Dinner Available\r\n•  Jain Meals Available (On Request)\r\n•  Tea, Coffee & Light Snacks Served Throughout the Day\r\n•  Room Service Available During Designated Hours\r\n•  Clean & Family-Friendly Dining Space', 'Check-in Time: 12:00 PM\r\nCheck-out Time: 11:00 AM\r\nGuests are required to present a valid ID proof at the time of check-in.\r\nLoud music or parties in rooms are not permitted.\r\nOutside food is generally not allowed.\r\nThe hotel may request a security deposit at check-in (refundable at checkout).'),
(2, 1, 'Hotel Sahyog', 'Near Bus Stand / Market Area, Main City', 3.7, 2600.00, '3 Star', '1762750480_4s1.jpg,1762750480_4s2.jpg,1762750480_5s1.jpg', 'Hotel Sahyog is a budget-friendly 3-star property offering clean, spacious and comfortable rooms ideal for family, couples, and group travelers. The hotel features well-maintained interiors, friendly staff, and quick room service to ensure a pleasant stay for every guest. Its central location near the city market and transportation points makes it a convenient choice for tourists.', 'Clean and Comfortable Rooms, Air Conditioning, Free WiFi, Complimentary Breakfast, Room Service (Limited Hours), 24-hour Front Desk, Daily Housekeeping, Free Parking, Television with Cable Channels, Laundry Service (Paid)', 'The hotel features an in-house multi-cuisine restaurant serving fresh and hygienic meals throughout the day. Guests can enjoy a variety of Indian vegetarian and non-vegetarian dishes along with snacks and beverages. Room service is available during restaurant hours.\r\n\r\n• In-House Restaurant\r\n• Breakfast Available (Buffet/À la carte)\r\n• Pure Veg Options Available\r\n• North Indian, Chinese & Local Cuisine', '• Check-in Time: 12:00 PM\r\n• Check-out Time: 11:00 AM\r\n• Valid ID Proof (Aadhar / Driving License / Passport) is mandatory for check-in\r\n• Pets are not allowed\r\n• Smoking allowed only in designated areas'),
(7, 1, 'Lemon Tree Hotel, Dehradun', 'Pacific Mall, Jakhan, Rajpur Road, Dehradun', 4.3, 6000.00, '4 Star', '1762857473_4s2.jpg,1762860847_4s1.jpg,1762860851_4s1.jpg', 'It is described as being “atop the award-winning and Upper Midscale Pacific Mall on Rajpur Road, a premium area of the city”. Rooms & suites: offers a range of room types—from Superior (≈36 m²) up to Deluxe Suite (≈91 m²) with amenities like tea/coffee maker, minibar, free WiFi, safe, etc. Guest review highlight: “49 spacious and smartly furnished rooms and suites with a magnificent view that let the outdoors in.', 'Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, 24-hour Room Service, Multi-cuisine Restaurant and Bar, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, Free On-site Parking, Conference Halls / Event Venues', 'The hotel features at least one in-house restaurant and a snack/cafe area\r\nThere is room service available and the café/snack bar supports lighter meals. \r\nKAYAK\r\nAccording to a review: “Food was very tasty and has variety to choose for breakfast.” \r\nMakeMyTrip\r\nAdditional detail: On Agoda, the breakfast supplement is noted as approx ₹609 for adults if not included in the room rate. ', 'Check-in Time: 12:00 PM Check-out Time: 11:00 AM Guests are required to present a valid ID proof at the time of check-in. Loud music or parties in rooms are not permitted. Outside food is generally not allowed. The hotel may request a security deposit at check-in (refundable at checkout).'),
(8, 1, 'Hotel Sai', 'Located in a prime and easily accessible area of the city', 4.7, 5000.00, '4 Star', '1762860961_4s1.jpg,1762860961_4s2.jpg', 'Hotel Sai is a modern and well-appointed 4-star property offering comfort, convenience, and warm hospitality. Designed for both leisure and business travelers, the hotel features elegantly furnished rooms with contemporary decor, soothing ambiance, and professional service. Guests enjoy easy access to local attractions, transport facilities, and popular markets.', 'Clean and Comfortable Rooms, 24-hour Front Desk, Daily Housekeeping, Free Parking, Laundry Service (Paid), Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, High-speed WiFi and Smart TVs, Conference Halls / Event Venues', 'The hotel features an in-house multi-cuisine restaurant serving Indian, Chinese, Continental, and local mountain specialties. A complimentary breakfast is provided for all guests, and room service is available during designated hours.', 'Check-in Time: 12:00 PM Check-out Time: 11:00 AM Guests are required to present a valid ID proof at the time of check-in. Loud music or parties in rooms are not permitted. Outside food is generally not allowed. The hotel may request a security deposit at check-in (refundable at checkout).'),
(9, 1, 'hotel Line', 'Rajpur Road, Dehradun', 4.9, 5500.00, '5 Star', '1762861211_4s2.jpg,1762864423_5s1.jpg,1762864423_5s2.jpg', 'Lemon Tree Hotel is located Pacific Mall, offering stylish interiors and serene valley views. Ideal for both leisure and business travelers, the property provides an upscale stay with convenient access to shopping, dining, and tourist attractions.', 'Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, 24-hour Room Service, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, Free On-site Parking, High-speed WiFi and Smart TVs, Conference Halls / Event Venues', 'The hotel provides a multi-cuisine restaurant serving buffet breakfast, à-la-carte meals, and specialty dishes. In-room dining is available 24/7.', 'Check-in: 2:00 PM\r\nCheck-out: 12:00 PM\r\nGovernment-approved ID mandatory\r\nPets not allowed'),
(10, 1, 'Hotel J.W. Marriott', 'Pacific Mall, Rajpur Road, Dehradun,', 4.9, 6000.00, '5 Star', '1762862814_4s2.jpg', 'JW Marriott Mussoorie Walnut Grove Resort & Spa is a luxury hillside resort located in the serene lap of the Himalayas. Known for its world-class hospitality, panoramic mountain views, and elegant interiors, it is ideal for family vacations, romantic getaways, and exclusive corporate retreats.', 'Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, 24-hour Room Service, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, Free On-site Parking, High-speed WiFi and Smart TVs, Conference Halls / Event Venues', 'The resort hosts multiple fine-dining restaurants, specialized live kitchens, bakery lounge, and themed dinner nights. Guests can enjoy international, continental, North-Indian, and handcrafted gourmet menus. 24-hour in-room dining is available.', 'Check-in: 2:00 PM\r\nCheck-out: 12:00 Pm\r\nGovernment-approved ID mandatory\r\n\r\nPets not allowed'),
(11, 2, 'hotel Lion', 'Pacific Mall, Rajpur Road, Dehradun,', 3.3, 2200.00, '3 Star', '1762862826_4s2.jpg', 'Hotel Lion is a comfortable and budget-friendly hotel located in North Goa, offering clean rooms, basic modern amenities, and a calm stay experience close to popular beaches. The property is suitable for families, couples, and group travelers who want an affordable stay near major tourist spots, markets, and restaurants.', 'Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, 24-hour Room Service, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, Free On-site Parking, High-speed WiFi and Smart TVs, Conference Halls / Event Venues', 'The hotel has an in-house multi-cuisine restaurant serving Indian, Goan, and Continental dishes. Buffet breakfast is available daily, and guests may also order meals through limited-hours room service.', 'Check-in: 2:00 PM\r\nCheck-out: 12:00 PM\r\nGovernment-approved ID mandatory\r\nPets not allowed'),
(13, 2, 'Hotel Pearl Goa Resort', 'Located in a prime and easily accessible area of the city', 4.7, 4000.00, '4 Star', '1762862855_4s1.jpg,1762862855_4s2.jpg', 'Hotel Sai is a modern and well-appointed 4-star property offering comfort, convenience, and warm hospitality. Designed for both leisure and business travelers, the hotel features elegantly furnished rooms with contemporary decor, soothing ambiance, and professional service. Guests enjoy easy access to local attractions, transport facilities, and popular markets.', 'Clean and Comfortable Rooms, 24-hour Front Desk, Daily Housekeeping, Free Parking, Laundry Service (Paid), Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, High-speed WiFi and Smart TVs, Conference Halls / Event Venues', 'The hotel features an in-house multi-cuisine restaurant serving Indian, Chinese, Continental, and local mountain specialties. A complimentary breakfast is provided for all guests, and room service is available during designated hours.', 'Check-in Time: 12:00 PM Check-out Time: 11:00 AM Guests are required to present a valid ID proof at the time of check-in. Loud music or parties in rooms are not permitted. Outside food is generally not allowed. The hotel may request a security deposit at check-in (refundable at checkout).'),
(15, 2, 'Hotel Rajpurohit', 'Located in a prime and easily accessible area of the city', 4.3, 4400.00, '4 Star', '1762867146_5s5.jpg', 'Hotel Rajpurohit is a premium 4-star property offering a comfortable and refined stay experience with modern interiors and a warm hospitality environment. The hotel features spacious rooms, elegant décor, and a calm ambience that caters to families, couples, and business travelers. Located close to popular tourist attractions and marketplaces, the property ensures a convenient and memorable stay.', 'Air Conditioning, Complimentary Breakfast, Room Service (Limited Hours), 24-hour Front Desk, Free Parking, Television with Cable Channels, Laundry Service (Paid), Spacious and Modern Rooms, 24-hour Room Service, Swimming Pool, Fitness Centre / Gym', 'Daily Buffet Breakfast Available\r\n Lunch & Dinner\r\nPure Veg / Non-Veg Options Available (Depending on Hotel Policy)', 'Check-in Time: 12:00 PM\r\nCheck-out Time: 11:00 AM\r\nGuests are required to present a valid ID proof at the time of check-in.\r\nLoud music or parties in rooms are not permitted.\r\nOutside food is generally not allowed.\r\nThe hotel may request a security deposit at check-in (refundable at checkout).'),
(16, 2, 'Hotel Asia', 'Candolim / Calangute / Baga belt, North Goa', 3.6, 3500.00, '3 Star', '1762867257_5s5.jpg', 'Hotel Asia is a comfortable and budget-friendly hotel located close to major beaches and local attractions in Goa. The property offers neat and well-maintained rooms, friendly service, and a peaceful environment suitable for families, couples, and group travelers. It provides an ideal stay for guests looking for a simple and relaxing accommodation at an affordable price.', 'Clean and Comfortable Rooms, Air Conditioning, Free WiFi, Complimentary Breakfast, Room Service (Limited Hours), Free Parking, Television with Cable Channels, Laundry Service (Paid)', 'The hotel features an in-house multi-cuisine restaurant serving Indian, Chinese, Continental, and local mountain specialties. A complimentary breakfast is provided for all guests, and room service is available during designated hours.', 'Check-in Time: 12:00 PM Check-out Time: 11:00 AM Guests are required to present a valid ID proof at the time of check-in. Loud music or parties in rooms are not permitted. Outside food is generally not allowed. The hotel may request a security deposit at check-in (refundable at checkout).'),
(17, 2, 'Hotel Acacia', 'Main Candolim Bus Stop Junction, Fort Aguada Road, Candolim', 4.8, 6600.00, '5 Star', '1762921442_ah1.jpg,1762921442_ah2.jpg,1762921442_ah3.jpg', 'Located just a short walk from the beautiful Candolim Beach, The Acacia Hotel & Spa, Goa is a stylish 4-star boutique property offering the perfect mix of comfort, convenience, and modern luxury. Nestled in the heart of North Goa’s vibrant Candolim area, this hotel is ideal for travelers seeking a relaxing stay with easy access to Goa’s nightlife, beaches, and local attractions.', 'Multi-cuisine Restaurant and Bar, Swimming Pool, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, 24-hour Butler Service, Fine Dining Restaurants and Bars, Spa and Wellness Centre, High-speed WiFi and Smart TVs, Conference Halls / Event Venues, Complimentary Breakfast Buffet, 24-hour Concierge, Daily Housekeeping and Turndown Service, Mini Bar and Coffee Machine in Room', 'At The Acacia Hotel & Spa, Goa, dining is an experience that blends global flavors with the laid-back Goan vibe. The hotel features multiple dining options, including a rooftop restaurant, bar, and café, each offering a distinct culinary experience for guests throughout the day.', 'Check-in Time: 12:00 PM\r\nCheck-out Time: 11:00 AM\r\nGuests are required to present a valid ID proof at the time of check-in.\r\nLoud music or parties in rooms are not permitted.\r\nOutside food is generally not allowed.\r\nThe hotel may request a security deposit at check-in (refundable at checkout).'),
(18, 3, 'Hotel Lakeview', 'West Lake Road, Ooty – 643 004, Tamil Nadu', 3.3, 2100.00, '3 Star', '1762921805_o1.jpg,1762921805_o2.jpg,1762921805_o3.jpg', 'The property spans around 8 acres on the terraced slopes of a hill overlooking Ooty Lake and the surrounding valley. It’s conveniently close to central Ooty (bus stand, boathouse) making it accessible while still offering a hillside, scenic retreat. ', 'Clean and Comfortable Rooms, Air Conditioning, Free WiFi, Complimentary Breakfast, Room Service (Limited Hours), 24-hour Front Desk, Free Parking, Television with Cable Channels, Laundry Service (Paid)', 'Dining is catered via an in-house restaurant and room service. The restaurant, called The Supper Club, serves multi-cuisine menus: Indian, Chinese, Continental.', '• Check-in Time: 12:00 PM\r\n• Check-out Time: 11:00 AM\r\n• Valid ID Proof (Aadhar / Driving License / Passport) is mandatory for check-in\r\n• Pets are not allowed\r\n• Smoking allowed only in designated areas'),
(19, 3, 'Hotel Darshan', 'Woodcock Road, near Ooty Lake, Ooty,', 3.5, 2400.00, '3 Star', '1762922162_oo1.jpg,1762922162_oo2.jpg,1762922162_oo3.jpg', 'Hotel Darshan is one of Ooty’s popular 3-star lake-view properties, ideally located near the Ooty Boathouse. The hotel offers a comfortable stay with scenic views of Ooty Lake and surrounding hills.\r\nRooms are elegantly designed with wooden interiors, warm lighting, and large windows for natural views. It’s a family-friendly hotel providing modern amenities at affordable prices.', 'Clean and Comfortable Rooms, Air Conditioning, Free WiFi, Complimentary Breakfast, Room Service (Limited Hours), 24-hour Front Desk, Daily Housekeeping, Free Parking, Television with Cable Channels, Laundry Service (Paid)', 'South Indian: Dosa, Idli, Pongal, Sambhar, Rasam\r\nNorth Indian: Paneer Butter Masala, Dal Tadka, Roti, Naan\r\nChinese: Fried Rice, Noodles, Manchurian\r\nContinental: Light snacks, soups, sandwiches\r\nLake-view indoor restaurant with glass panels\r\nIn-room dining/room service available', '• Check-in Time: 12:00 PM\r\n• Check-out Time: 11:00 AM\r\n• Valid ID Proof (Aadhar / Driving License / Passport) is mandatory for check-in\r\n• Pets are not allowed\r\n• Smoking allowed only in designated areas'),
(20, 2, 'Hotel Taj Exotica', 'Beach Road, Calwaddo, Benaulim, Goa', 4.5, 5500.00, '5 Star', '1762921163_5s8.jpg,1762921163_taj2.jpg,1762921163_taj3.jpeg,1762921163_Taj-Exotica-Resort-Spa-Goa.jpg', 'Nestled on the serene sands of Benaulim Beach in South Goa, Taj Exotica Resort & Spa is a luxurious 5-star beachfront retreat that blends Goan charm with world-class elegance. Surrounded by 56 acres of lush gardens and overlooking the Arabian Sea, this resort offers a tranquil escape from the hustle of city life.The resort features spacious Mediterranean-style villas and rooms, each designed with warm interiors, private balconies, and modern amenities.', 'In-house Restaurant or Café, Free Parking, Multi-cuisine Restaurant and Bar, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, Free On-site Parking, 24-hour Butler Service, Fine Dining Restaurants and Bars, Spa and Wellness Centre, Indoor or Outdoor Swimming Pool, Fitness Centre / Yoga Room, Valet Parking, High-speed WiFi and Smart TVs, Conference Halls / Event Venues, Complimentary Breakfast Buffet, 24-hour Concierge, Daily Housekeeping and Turndown Service, Mini Bar and Coffee Machine in Room', 'Beach-front grill restaurant: seasonal, live‐grill using local seafood and meats, positioned right on the sand. \r\nGood for romantic dinners, sunset views, seaside ambience.', 'Check-in Time: 12:00 PM\r\nCheck-out Time: 11:00 AM\r\nGuests are required to present a valid ID proof at the time of check-in.\r\nLoud music or parties in rooms are not permitted.\r\nOutside food is generally not allowed.\r\nThe hotel may request a security deposit at check-in (refundable at checkout).'),
(23, 3, 'Sterling Ooty Fern Hill', 'No. 73, Kundah House Road, Fern Hill, Ooty, Tamil Nadu', 4.3, 4400.00, '4 Star', '1762922484_ooty4.jpg,1762922484_ooty5.jpg,1762922484_ooty6.jpg', 'Sterling Ooty Fern Hill is a premium 4-star hill resort located on the scenic Fern Hill slopes. The resort overlooks the beautiful Nilgiri mountains and offers elegant rooms, suites, and cottages designed for both comfort and leisure.', 'Clean and Comfortable Rooms, Free Parking, Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, 24-hour Room Service, Multi-cuisine Restaurant and Bar, Free On-site Parking, Fine Dining Restaurants and Bars', 'Serves multi-cuisine dishes: Indian, Chinese, Continental, and South Indian.\r\nOffers both buffet and à la carte dining.\r\nPopular dishes: Kavipoo Milagu Peratal (cauliflower with pepper) and Meen Varuval (spicy fried fish).\r\nGuests can also enjoy drinks and snacks at the Sterling Local Bar & Lounge, known for its cozy atmosphere.', '• Check-in Time: 12:00 PM\r\n• Check-out Time: 11:00 AM\r\n• Valid ID Proof (Aadhar / Driving License / Passport) is mandatory for check-in\r\n• Pets are not allowed\r\n• Smoking allowed only in designated areas'),
(25, 3, 'hotel  The Monarch Ooty', 'Havelock Road, Ooty, Tamil Nadu.', 4.9, 6600.00, '5 Star', '1762923869_monarch.jpg,1762923869_the-monarch-ooty.jpg,1762924012_monarch.jpg,1762924012_monarch-ooty.jpg,1762924012_the-monarch-ooty.jpg', 'The Monarch Ooty, part of the Mithun Group of Hotels, is a premium hill-station', 'Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, 24-hour Room Service, Multi-cuisine Restaurant and Bar, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, Free On-site Parking, Concierge Service, Luxury Rooms and Suites, Fine Dining Restaurants and Bars, Spa and Wellness Centre, Fitness Centre / Yoga Room, Valet Parking, High-speed WiFi and Smart TVs, Complimentary Breakfast Buffet, Daily Housekeeping and Turndown Service', 'The Monarch Ooty has a multi-cuisine restaurant named “Hello” that serves both vegetarian and non-vegetarian fare. The menu includes Indian (North & South), Chinese, Continental, Tandoori items, Jain food options, confectionery and savoury delicacies', '• Check-in Time: 12:00 PM\r\n• Check-out Time: 11:00 AM\r\n• Valid ID Proof (Aadhar / Driving License / Passport) is mandatory for check-in\r\n• Pets are not allowed\r\n• Smoking allowed only in designated areas'),
(26, 3, 'Royal Orchid Metropole Mysore', 'Sayyaji Rao Road', 4.6, 6600.00, '5 Star', '1762923429_5s1.jpg,1762923429_5s2.jpg,1762923429_5s3.jpg', 'This hotel is a 5-star property that combines a heritage-style building and modern hotel amenities. It’s centrally located, making it good for sightseeing and staying close to major attractions in Mysore.', 'Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, 24-hour Room Service, Multi-cuisine Restaurant and Bar, Swimming Pool, Fitness Centre / Gym, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service, Free On-site Parking, Concierge Service, Luxury Rooms and Suites, 24-hour Butler Service, Fine Dining Restaurants and Bars, Spa and Wellness Centre, Indoor or Outdoor Swimming Pool, Fitness Centre / Yoga Room, Valet Parking, High-speed WiFi and Smart TVs, Conference Halls / Event Venues, Complimentary Breakfast Buffet, 24-hour Concierge, Daily Housekeeping and Turndown Service, Mini Bar and Coffee Machine in Room', 'The hotel features a multi-cuisine restaurant, offering Indian, Chinese and Continental dishes. Guests often mention the dining experience being comfortable for both families and business stays.', '• Check-in Time: 12:00 PM\r\n• Check-out Time: 11:00 AM\r\n• Valid ID Proof (Aadhar / Driving License / Passport) is mandatory for check-in\r\n• Pets are not allowed\r\n• Smoking allowed only in designated areas'),
(27, 3, 'Fortune Resort Sullivan Court ', '123, Selbourne Road, Opposite Rose Garden, Ooty – 643001, Tamil Nadu', 4.4, 4999.00, '4 Star', '1762922759_fortune-resort-sullivan.jpg,1762922759_fortune-resort-sullivan1.jpg,1762922759_fortune-resort-sullivan2.jpg', 'Fortune Resort Sullivan Court is a stylish 4-star property nestled in the heart of Ooty, surrounded by rolling hills and the famous Rose Garden. It’s known for its combination of colonial charm and modern luxury.', '24-hour Front Desk, Daily Housekeeping, Free Parking, Spacious and Modern Rooms, Air Conditioning with Climate Control, High-speed WiFi, Banquet Hall / Meeting Rooms, Laundry and Dry-cleaning Service', 'Offers all-day multi-cuisine dining with breakfast, lunch, and dinner buffets.\r\nMenu includes North & South Indian, Chinese, and Continental cuisines.\r\nKnown for its fresh bakery items and hot beverages.', '• Check-in Time: 12:00 PM\r\n• Check-out Time: 11:00 AM\r\n• Valid ID Proof (Aadhar / Driving License / Passport) is mandatory for check-in\r\n• Pets are not allowed\r\n• Smoking allowed only in designated areas');

--